#!/usr/bin/env python3
"""
Contextual Orchestration Agent PR Reviewer for AWS Data Perimeters.
Uses an LLM (Large Language Model) to perform non-deterministic, intent-aware data path reasoning
over synthesized CloudFormation diffs, evaluating them against natural-language policy objectives
and exception manifests.
"""

import json
import os
import sys
import urllib.request
import urllib.error

POLICY_OBJECTIVE_PATH = os.path.join("policies", "data_perimeter_objective.json")
EXCEPTION_MANIFEST_PATH = os.path.join("policies", "exception_manifest.json")

SYSTEM_PROMPT = """You are a DevSecOps Security Orchestration Agent powered by a Large Language Model (LLM) reviewing an Infrastructure-as-Code (IaC) diff for AWS Data Perimeter compliance.

Your task is to perform contextual cross-resource data-path reasoning, interpret developer intent, and identify potential external exfiltration vectors.

CRITICAL INSTRUCTION:
Every finding header MUST explicitly indicate that the review was generated by an LLM Agent by appending " (Generated by LLM Orchestration Agent)" to the title.

EVALUATION RULES:
1. Deterministic linters check syntax in isolation. You evaluate intent, cross-resource data paths, and organizational policy objectives.
2. Check if S3 write grants (s3:PutObject, s3:*) contain required organizational condition keys (aws:PrincipalOrgID or aws:ResourceOrgID).
3. If condition keys are missing, check if the destination bucket ARN matches an active entry in the Approved Vendor Exception Manifest.
4. Output your analysis as a structured Pull Request Markdown comment.

If compliant (with condition keys present):
## Data-Perimeter Review Finding: Compliant (Generated by LLM Orchestration Agent)
**Status:** PASSED

If matching an approved exception:
## Data-Perimeter Review Finding: Approved Vendor Exception Matched (Generated by LLM Orchestration Agent)
**Status:** PASSED (APPROVED EXCEPTION)
Provide Matched Exception ID, Vendor Name, Approval Details, and Action.

If missing condition keys and NOT an approved exception:
## Data-Perimeter Review Finding: Potential External Exfiltration Path (Generated by LLM Orchestration Agent)
**Status:** NEEDS HUMAN REVIEW
Provide Affected resources, Risk explanation, Remediation advice, and Required action.
"""

def load_file_content(filepath):
    if not os.path.exists(filepath):
        return ""
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read()

def call_llm_agent(user_prompt):
    """
    Invokes LLM API (DeepSeek, OpenAI, Gemini). Strictly requires an API key.
    """
    deepseek_key = os.environ.get("DEEPSEEK_API_KEY")
    openai_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("LLM_API_KEY")

    if deepseek_key:
        url = "https://api.deepseek.com/chat/completions"
        model = "deepseek-chat"
        api_key = deepseek_key
        print("[Agent] Invoking DeepSeek LLM API (deepseek-chat)...")
    elif openai_key:
        url = "https://api.openai.com/v1/chat/completions"
        model = "gpt-4o"
        api_key = openai_key
        print("[Agent] Invoking OpenAI LLM API (gpt-4o)...")
    else:
        raise RuntimeError("[Error] No LLM API key found in environment variables (DEEPSEEK_API_KEY / OPENAI_API_KEY / LLM_API_KEY required).")

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.1
    }

    try:
        req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"), headers=headers)
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return data["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode('utf-8')
        raise RuntimeError(f"[Error] LLM API HTTP {e.code}: {error_body}")
    except Exception as e:
        raise RuntimeError(f"[Error] LLM API Call Failed: {e}")

def main():
    template_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join("cdk", "cdk.out", "DataPerimeterStack.template.json")
    print(f"[Agent] Orchestration Agent initializing for: {template_path}")

    template_content = load_file_content(template_path)
    policy_obj = load_file_content(POLICY_OBJECTIVE_PATH)
    exceptions_manifest = load_file_content(EXCEPTION_MANIFEST_PATH)

    user_prompt = f"""EVALUATE THIS IAC DIFF FOR DATA PERIMETER COMPLIANCE:

--- ORGANIZATIONAL POLICY OBJECTIVE ---
{policy_obj}

--- APPROVED VENDOR EXCEPTION MANIFEST ---
{exceptions_manifest}

--- SYNTHESIZED CLOUDFORMATION TEMPLATE ---
{template_content}
"""

    llm_output = call_llm_agent(user_prompt)

    print("\n" + "=" * 60)
    print(llm_output)
    print("=" * 60 + "\n")

    with open("finding_comment.md", "w", encoding="utf-8") as f:
        f.write(llm_output)
    print("[Agent] Review finding written to finding_comment.md")

if __name__ == "__main__":
    main()
